server:
  port: 8081
  servlet.context-path: /repair-service

spring:
  security:
    user: 
      name: user1
      password: mypass

springdoc.api-docs.enabled: false

---
spring:
  profiles: devel

  security: 
    user: 
      name: user2
      password: test
  
---
spring:
  profiles: e2e

app:
  dummy.login.active: true


---
spring:
  profiles: test

server:
  port: 1234

---
verwaltung:
  rest:
    url: https://123.123.123.123:1234/repair-request 
    connect-timeout-millis: 1000
    read-timeout-millis: 2000
